# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-11 12:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0017_auto_20170110_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoservice',
            name='boundary',
            field=models.TextField(blank=True, null=True, verbose_name='boundaries polygon (GeoJSON)'),
        ),
        migrations.AddField(
            model_name='geoservice',
            name='extent',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='service extent'),
        ),
    ]
